int main(void) {
    __asm__(
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    "nop  \n\t"
    );

    return 0;
}
